FORMAT: X-1A
HOST: http://api-beta.ly.g0v.tw

# TW ly api v0
online test of [beta API](http://api-beta.ly.g0v.tw)
This is beta version of api.ly.g0v.tw. Written in [apiblueprint](http://apiblueprint.org/) by [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax.
Every API have following attributes:

+ paging (Object)
    + count (integer) ... Total number of entries
    + l (integer) ... Number of entries list in entries.
    + sk (integer) ... Start offset of entries. Start from 0
        + Sample Page 1: http://api-beta.ly.g0v.tw/v0/collections/calendar?l=10&sk=0
        + Sample Page 2: http://api-beta.ly.g0v.tw/v0/collections/calendar?l=10&sk=10
        + Sample Page 3: http://api-beta.ly.g0v.tw/v0/collections/calendar?l=10&sk=20

+ entries (Array)
    + Every entry have it's own attributes, see following list and example. 

##### Retrieve an API [GET]


# GET /v0/
Show specific version of API.
+ Response 200 (application/json)

# GET /v0/collections/
List all avaible collection of current version.
+ Response 200 (application/json)

# Group ivod
+ This is the api group of ivod (影片)
+ ivod為立法院的議事轉播公開影片，每一個entry包含影片的錄製時間、影片種類、原始連結、縮圖等資訊。
資料來源:立法院議事轉播 http://ivod.ly.gov.tw/

## GET /v0/collections/ivod/
Example: /v0/collections/ivod 
+ Response 200 (application/json)

# Group calendar
+ This is the api group of calendar (行程)
+ 立法院最新的公開行程
資料來源: http://www.ly.gov.tw/01_lyinfo/0101_lynews/lynewsList.action

## GET /v0/collections/calendar/
Example: /v0/collections/calendar?q={"type":"hearing"} 
+ Response 200 (application/json)

# Group motions
+ This is the api group of motions (議案/公報)
+ 立法院將議事的紀錄撰寫成公報，供所有公民檢閱。
資料來源: http://misq.ly.gov.tw + http://npl.ly.gov.tw

## GET /v0/collections/motions/
Example: /v0/collections/motions?q={"bill_id":"1011011071000200"} 
+ Response 200 (application/json)

# Group bills
+ This is the api group of bills (提案)
+ 立法院黨團、委員、政府提出的提案，可能是法律案、預算案、其他案、宣戰案...等。
資料來源: http://misq.ly.gov.tw + http://npl.ly.gov.tw

## GET /v0/collections/bills/
Example: /v0/collections/bills 
+ Response 200 (application/json)

### GET /v0/collections/bills/{bill_id}/
Example: http://api-beta.ly.g0v.tw/v0/collections/bills/1021021070200400/ 
+ Response 200 (application/json)

#### GET /v0/collections/bills/{bill_id}/data
Example: http://api-beta.ly.g0v.tw/v0/collections/bills/1021021070200400/data 
+ Response 200 (application/json)

#### GET /v0/collections/bills/{bill_id}/doc
Example: http://api-beta.ly.g0v.tw/v0/collections/bills/1021021070200400/doc 
+ Response 200 (application/json)

#### GET /v0/collections/bills/{bill_id}/motions
Example: http://api-beta.ly.g0v.tw/v0/collections/bills/1021021070200400/motions 
+ Response 200 (application/json)

# Group sittings
+ This is the api group of sittings (會議)
+ 立法院以會期為單位舉辦每個會議，一次會議可能會分多天進行，此 api 包含該次會議的所有相關資訊，如議程、相關影像等。

## GET /v0/collections/sittings/
Example: /v0/collections/sittings 
+ Response 200 (application/json)

### GET /v0/collections/sittings/{id}/
Example: http://api-beta.ly.g0v.tw/v0/collections/sittings/08-04-YS-06/ 
+ Response 200 (application/json)

#### GET /v0/collections/sittings/{id}/dates
Example: http://api-beta.ly.g0v.tw/v0/collections/sittings/08-04-YS-06/dates 
+ Response 200 (application/json)

#### GET /v0/collections/sittings/{id}/videos
Example: http://api-beta.ly.g0v.tw/v0/collections/sittings/08-04-YS-06/videos 
+ Response 200 (application/json)

#### GET /v0/collections/sittings/{id}/motions
Example: http://api-beta.ly.g0v.tw/v0/collections/sittings/08-04-YS-06/motions 
+ Response 200 (application/json)

