FORMAT: X-1A
HOST: http://api-beta.ly.g0v.tw

# TW ly api v0
online test of [beta API](http://api-beta.ly.g0v.tw)
This is beta version of api.ly.g0v.tw. Written in [apiblueprint](http://apiblueprint.org/) by [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax.

# GET /v0/
Show specific version of API.
+ Response 200 (application/json)

# GET /v0/collections/
List all avaible collection of current version.
+ Response 200 (application/json)

This is the api group of ivod
+ Response 200 (application/json)


## GET /v0/collections/ivod/
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/ivod/ 
+ Response 200 (application/json)

This is the api group of calendar
+ Response 200 (application/json)


## GET /v0/collections/calendar/
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/calendar/ 
+ Response 200 (application/json)

This is the api group of motions
+ Response 200 (application/json)


## GET /v0/collections/motions/
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/motions/ 
+ Response 200 (application/json)

This is the api group of bills
+ Response 200 (application/json)


## GET /v0/collections/bills/
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/bills/ 
+ Response 200 (application/json)

### GET /v0/collections/bills/{bill_id}/
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/bills/{bill_id}/ 
+ Response 200 (application/json)

#### GET /v0/collections/bills/{bill_id}/data
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/bills/{bill_id}/data 
+ Response 200 (application/json)

#### GET /v0/collections/bills/{bill_id}/doc
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/bills/{bill_id}/doc 
+ Response 200 (application/json)

#### GET /v0/collections/bills/{bill_id}/motions
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/bills/{bill_id}/motions 
+ Response 200 (application/json)

This is the api group of sittings
+ Response 200 (application/json)


## GET /v0/collections/sittings/
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/sittings/ 
+ Response 200 (application/json)

### GET /v0/collections/sittings/{id}/
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/sittings/{id}/ 
+ Response 200 (application/json)

#### GET /v0/collections/sittings/{id}/dates
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/sittings/{id}/dates 
+ Response 200 (application/json)

#### GET /v0/collections/sittings/{id}/videos
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/sittings/{id}/videos 
+ Response 200 (application/json)

#### GET /v0/collections/sittings/{id}/motions
Try real api path: http://api-beta.ly.g0v.tw/v0/collections/sittings/{id}/motions 
+ Response 200 (application/json)

