site :opscode

cookbook 'postgresql'
cookbook 'git'
cookbook 'runit'
cookbook 'python'
cookbook 'pgrest', github: 'clkao-cookbooks/pgrest'
cookbook 'nodejs', github: 'phlipper/chef-nodejs'
cookbook 'ly.g0v.tw', path: '.'
