site :opscode

cookbook 'postgresql', '3.0.4'
cookbook 'git'
cookbook 'runit'
cookbook 'python'
cookbook 'pgrest', github: 'clkao-cookbooks/pgrest'
cookbook 'nodejs', github: 'phlipper/chef-nodejs'
cookbook 'ly.g0v.tw', path: '.'
cookbook 'database', github: 'clkao-cookbooks/database'
cookbook 'cron'
cookbook 'nginx', github: 'opscode-cookbooks/nginx', ref: 'bccc005adf8805dbea46b44426dea7ff6d2389d0'
cookbook 'libreoffice', github: 'Youscribe/libreoffice-cookbook'
cookbook 'casperjs', github: 'jenkinslaw/casperjs-cookbook'
