# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-12.04.3"
  config.vm.box_url = "https://s3-eu-west-1.amazonaws.com/ffuenf-vagrant-boxes/ubuntu/ubuntu-12.04.3-server-amd64.box"
  config.vm.network :forwarded_port, host: 6988, guest: 80
  config.vm.network :forwarded_port, host: 6989, guest: 1935
  config.vm.network :forwarded_port, host: 6990, guest: 8090
  config.vm.synced_folder "../../..", "/vagrant_git"
  config.cache.auto_detect = true
  config.berkshelf.enabled = true
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.vm.provision :chef_solo do |chef|
    chef.data_bags_path = "data_bags"
    chef.add_recipe 'pgrest'
    chef.add_recipe 'monit'
    chef.add_recipe 'ly.g0v.tw::apiserver'
    ### Enable the following recipes for worker and streaming related services
    # chef.add_recipe 'ly.g0v.tw::worker'
    # chef.add_recipe 'ly.g0v.tw::stream'
    # chef.add_recipe 'ly.g0v.tw::stream-worker'

    chef.json.merge!(JSON.parse(File.read("./dna.json")))
  end
end
