# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "g0v"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/4339854/g0v/g0v-ubuntu-precise64.box"
  config.vm.network :forwarded_port, host: 6988, guest: 80
  config.vm.synced_folder "../../..", "/vagrant_git"
  config.cache.auto_detect = true
  config.berkshelf.enabled = true
  config.vm.provision :chef_solo do |chef|
  chef.add_recipe 'pgrest'
  chef.add_recipe 'ly.g0v.tw'

  chef.json.merge!(JSON.parse(File.read("./dna.json")))
  end
end
